#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSQX9u93RQhZCepjhbnoExwvxJdFsEE0Ulok"
APP_SECRET: "HS5ZHGvfLwWxlfadvUMSv2Iqi9WKTXIXTrm6kSSrT939YmFJD55dfxbYimMQrY5wVov38tsl07YTxH2zRU6qPu5KCckj3wIxz4HogDGPJBzi9F4RJeca3bZnKbZ2i76WHgQgqI8ZvmPmaUZ9LTwHHOc2wkREWtku/a2b7ZjFY+5wN+yaVjA="

#계좌번호 앞 8자리
CANO: "63982305"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1178582864485433435/IMm5m4CEZJhCUEsKtkGisZbfNbkMhFnel-slRNrq3T6zITJdc9eC2E9sl_xk2LvJgqB6"
